version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: opticours
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - opticours-network

  # Backend API
  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=opticours
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your_production_jwt_secret_here
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - opticours-network
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/exports:/app/exports

  # Frontend Next.js
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - opticours-network

volumes:
  postgres_data:

networks:
  opticours-network:
    driver: bridge 